### ISSUE TITLE
Water temp stuck at 225F 

### ISSUE THREAD

**Issue by mike240se** [rsnodgrass/hass-flo-water#10]
Just installed the integration via HACS and water pressure and flo rate seem correct but water temp is fixed at 225F so far, for the first hour after being installed.   I just logged in the website and it looks like maybe the reason is they removed the temp reading from the system???? (IDK why they would do that, why take away features, really odd)

**Comment by rsnodgrass** [comment]
I can confirm this is an issue on Flo's side.  They are returning a tempF of 146 for my device.  

Hopefully they add this back as I found it very useful...in fact it found an issue with the expansion tank with my hot water system since the temperature on the cold water plumbing raised much higher than expected.

Will leave this issue open for now, while we all wait for them to fix this.

**Comment by mike240se** [comment]
Yeah they need to add this back, I am going to email them since I pay  monthly and should be able to get a response.

It actually looks like I am not getting any data though, my pressure has been at 60.7 since I installed the integration and my GPM has never changed from 0, its a straight line.

**Comment by mike240se** [comment]
This is ridiculous, i already own a weather station for the outside temp.

"The water temperature was replaced with area temperature because many homeowners were complaining of missing freeze warnings due to the placement of their Flo device.  Some homes have hot water recirculating systems which would always keep the water temperature higher than it actually was.  Some devices were placed in crawl spaces or basements which were warmer than the actual water temp under the ground in the pipes which would also produce readings higher than normal.  As a result, we switched over the outside area temp so homeowners would have a reliable source for freezing conditions and they could take action to avoid a burst pipe.  Please contact us if there are additional questions that we can assist you with.  Thank you for your patience and have a great day!"

**Comment by rsnodgrass** [comment]
I agree!

Write into Flo support and say you don't want them to remove the water
temperature feature.

**Comment by mike240se** [comment]
yeah if they get enough emails like mine i think they will quickly turn it back on:

Thank you for your insight and feedback.  I will definitely present your request to the app and development team for review.  Hopefully, they can introduce an option between water temperature and area temperature in the future.  Please contact us if there are additional questions or concerns that we can assist you with.  Thank you for your patience and have a great day!

**Comment by rsnodgrass** [comment]
Flo still has not enabled a solution for water temperature.  As a proxy, perhaps we should return area temp like their app now does?
