### ISSUE TITLE
cannot import name 'ICON_FLOW_RATE' from 'pyflowater.const'

### ISSUE THREAD

**Issue by btuysser** [rsnodgrass/hass-flo-water#13]
Log Details (ERROR)
Logger: homeassistant.setup
Source: setup.py:258
First occurred: 10:26:21 AM (1 occurrences)
Last logged: 10:26:21 AM

Unable to prepare setup for platform flo.sensor: Platform not found (cannot import name 'ICON_FLOW_RATE' from 'pyflowater.const' (/usr/local/lib/python3.8/site-packages/pyflowater/const.py)).

**Comment by rsnodgrass** [comment]
Resolved in 3.0.4
